version: "3"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - database
    networks:
      - service-network
    environment:
      PG_PASSWORD: postgres
      PG_HOST: database
    volumes:
      - ./migrations:/app/migrations
  database:
    image: postgres:13.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - service-network
    volumes:
      - booking-database:/var/lib/postgresql/data
networks:
  service-network:
    driver: bridge
volumes:
  booking-database: